4825125910 <style> Ajustando schema de thema para desenvolvimento de …
GUIDEV19/controle-total-financas pull request #15
Opened 2023-07-23 03:02 UTC by GUIDEV19

…novo layout.

2023-07-24 22:10 UTC, thirc20 requested changes

2023-07-24 22:10 UTC, thirc20 commented on src/constants/themes.ts
> +                    color: "#FF9600",
Cor do texto do cartão de crédito inválida! correta: 001AFF

2023-07-24 22:10 UTC, thirc20 commented on src/constants/themes.ts
> +                    fontStyle: "italic",
Retirar o italico

2023-07-24 22:10 UTC, thirc20 commented on src/constants/themes.ts
> +                    fontStyle: "italic",
Retirar o italico

2023-07-26 01:02 UTC, thirc20 approved these changes

2023-07-26 01:07 UTC, thirc20 requested changes

2023-07-26 01:07 UTC, thirc20 commented on src/constants/themes.ts
> +                    backgroundColor: "#DAE8F7",
ambos os botões estão azul o color

2023-07-26 01:07 UTC, thirc20 commented on src/constants/themes.ts
> +                    color: "#001AFF",
ambos os botões estão azul o color

2023-07-26 02:16 UTC, GUIDEV19 commented on src/constants/themes.ts
> +                    color: "#001AFF",
Mas não é isso?

2023-07-26 02:16 UTC, GUIDEV19 commented on src/constants/themes.ts
> +                    color: "#001AFF",
Mudou no figma

2023-07-27 12:14 UTC, thirc20 approved these changes

2023-07-28 01:56 UTC, merged